sudo: false
language: node_js
node_js:
  - "0.12"
  - "4.2"
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"

notifications:
  email:
    - charlie.robbins@gmail.com
