sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"

before_install:
  - g++ --version
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"

notifications:
  email:
    - charlie.robbins@gmail.com
